### ISSUE TITLE
Using Hopcroft's minimization

### ISSUE THREAD

**Issue by MaiadaMahmoud** [xsc/lexington#2]
Hello

I'm trying to use just the hopcroft's minimization part but I'm new to clojure and I'm not sure how to do that using your library

Could you tell me how to do that?

**Comment by xsc** [comment]
Hey there,

I haven't had any contact with this library for years, so best I can offer is pointing you at the respective testcase here:

https://github.com/xsc/lexington/blob/master/test/lexington/fsm/minimize_tests.clj

Hope that helps!
Yannick

**Comment by MaiadaMahmoud** [comment]
Thanks for your help
